sudo: false
language: node_js
env:
- BITCORENODE_ENV=test BITCORENODE_ASSUME_YES=true
node_js:
  - "v0.12.7"
before_install:
  - git config --global user.email "dev@bitpay.com"
  - git config --global user.name "BitPay, Inc."
script:
  - _mocha -R spec integration/regtest.js
  - _mocha -R spec integration/regtest-node.js
  - _mocha -R spec --recursive
cache:
  directories:
    - cache
